### ISSUE TITLE
Error trying to get new translations

### ISSUE THREAD

**Issue by SergioAtSUSE** [openSUSE/landing-page#121]
# Error trying to get new translations

```
mansilla@copland:~/github/landing-page$ po/update_po.rb 
/usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- nokogiri (LoadError)
        from /usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from po/update_po.rb:23:in `<main>'
mansilla@copland:~/github/landing-page$
```

# Error trying to install nokogiri:

```
mansilla@copland:~/github/landing-page$ sudo gem install nokogiri                                                    
root's password:
Fetching: mini_portile2-2.1.0.gem (100%)
Successfully installed mini_portile2-2.1.0
Fetching: nokogiri-1.7.1.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby.ruby2.1 extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib64/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /usr/lib64/ruby/gems/2.1.0/gems/nokogiri-1.7.1 for inspection.
Results logged to /usr/lib64/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/nokogiri-1.7.1/gem_make.out
mansilla@copland:~/github/landing-page$
```

**Comment by lnussel** [comment]
sudo zypper in 'rubygem(nokogiri)'

**Comment by SergioAtSUSE** [comment]
Ok, that worked, but I had to install `gettext` too:

```
sudo zypper in 'rubygem(gettext)'
```

I add here in case someone else needs it and PR: https://github.com/openSUSE/landing-page/pull/123
